services:
  api:
    build: .
    container_name: mlops_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro
    environment:
      - PYTHONNUMBUFFERED=1
      - MODEL_PATH=/app/models/production.pt
    restart: unless-stopped
  ui:
    build: .
    container_name: mlops-ui
    ports:
      - "3000:3000"
    command: ["uvicorn", "template.ui_test:app", "--host", "0.0.0.0", "--port", "3000"]
    environment:
      - PYTHONNUMBUFFERED=1
      # UI will call api from name service from api container
      - API_BASE=http://api:8000
    depends_on:
      - api
    restart: unless-stopped